version: '3.8'

networks:
  studify-net:

services:
  eureka-server:
    image: ghcr.io/hsuncho/eureka-server:${TAG:-latest}
    env_file: [ ./.env ]
    ports: ["8761:8761"]
    networks: [ studify-net ]

  api-gateway:
    image: ghcr.io/hsuncho/api-gateway:${TAG:-latest}
    env_file: [ ./.env ]
    ports: ["8080:8080"]
    depends_on: [ eureka-server ]
    networks: [ studify-net ]

  user-service:
    image: ghcr.io/hsuncho/user-service:${TAG:-latest}
    env_file: [ ./.env ]
    depends_on: [ eureka-server ]
    networks: [ studify-net ]

  post-service:
    image: ghcr.io/hsuncho/post-service:${TAG:-latest}
    env_file: [ ./.env ]
    depends_on: [ eureka-server ]
    networks: [ studify-net ]

  notification-service:
    image: ghcr.io/hsuncho/notification-service:${TAG:-latest}
    env_file: [ ./.env ]
    depends_on: [ eureka-server ]
    networks: [ studify-net ]
